//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Console.ExternalWebServiceMessage {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/MyApp.Entities")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string authorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string author {
            get {
                return this.authorField;
            }
            set {
                if ((object.ReferenceEquals(this.authorField, value) != true)) {
                    this.authorField = value;
                    this.RaisePropertyChanged("author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExternalWebServiceMessage.IWSMessage")]
    public interface IWSMessage {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSMessage/DoWork", ReplyAction="http://tempuri.org/IWSMessage/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSMessage/DoWork", ReplyAction="http://tempuri.org/IWSMessage/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSMessage/GetMessageFromUsersFollow", ReplyAction="http://tempuri.org/IWSMessage/GetMessageFromUsersFollowResponse")]
        MyApp.Console.ExternalWebServiceMessage.Message[] GetMessageFromUsersFollow(string nickName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSMessage/GetMessageFromUsersFollow", ReplyAction="http://tempuri.org/IWSMessage/GetMessageFromUsersFollowResponse")]
        System.Threading.Tasks.Task<MyApp.Console.ExternalWebServiceMessage.Message[]> GetMessageFromUsersFollowAsync(string nickName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSMessage/SendMessage", ReplyAction="http://tempuri.org/IWSMessage/SendMessageResponse")]
        string SendMessage(string nickName, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSMessage/SendMessage", ReplyAction="http://tempuri.org/IWSMessage/SendMessageResponse")]
        System.Threading.Tasks.Task<string> SendMessageAsync(string nickName, string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSMessageChannel : MyApp.Console.ExternalWebServiceMessage.IWSMessage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSMessageClient : System.ServiceModel.ClientBase<MyApp.Console.ExternalWebServiceMessage.IWSMessage>, MyApp.Console.ExternalWebServiceMessage.IWSMessage {
        
        public WSMessageClient() {
        }
        
        public WSMessageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSMessageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMessageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMessageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public MyApp.Console.ExternalWebServiceMessage.Message[] GetMessageFromUsersFollow(string nickName) {
            return base.Channel.GetMessageFromUsersFollow(nickName);
        }
        
        public System.Threading.Tasks.Task<MyApp.Console.ExternalWebServiceMessage.Message[]> GetMessageFromUsersFollowAsync(string nickName) {
            return base.Channel.GetMessageFromUsersFollowAsync(nickName);
        }
        
        public string SendMessage(string nickName, string msg) {
            return base.Channel.SendMessage(nickName, msg);
        }
        
        public System.Threading.Tasks.Task<string> SendMessageAsync(string nickName, string msg) {
            return base.Channel.SendMessageAsync(nickName, msg);
        }
    }
}
